## 
## HTTPS 모의 애플리케이션
##
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-apl3
spec:
  replicas: 3
  selector:         # deployment - pod 대응용
    matchLabels:
      apl: web-apl3 # 파드와 일치해야 하는 라벨
  template:         ### 파드 템플릿 
    metadata:
      labels:
        apl: web-apl3   # 파드의 라벨
        app: expose     # 접근 폴리시로 공개 지정
    spec:
      containers:
      - name: nginx
        image: nginx:latest      # Nginx 공식 컨테이너
        ports:                     # 공개 포트
        - protocol: TCP            # TCP
          containerPort: 443       # HTTPS
        volumeMounts:                   ## 볼륨 마운트
        - name: nginx-conf              # 컨피그맵의 Vol 이름
          mountPath: /etc/nginx/conf.d  # 마운트 경로
        - name: tls-cert                # 시크릿 Vol 이름
          mountPath: /etc/cert          # 마운트 경로
      volumes:               ## 볼륨 정의 
      - name: nginx-conf     # Vol 이름 
        configMap:           # 컨피그맵을 지정
          name: nginx-conf   # 참조할 컨피그맵 이름
      - name: tls-cert       # Vol 이름
        secret:              # 시크릿 지정
          secretName: cert   # 참조할 시크릿 이름

