#
# 외부 공개용
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-apl1
spec:
  replicas: 1
  selector:
    matchLabels:
      web: web-apl1
      app: expose
  template:
    metadata:
      labels:
        web: web-apl1
        app: expose          # 외부 공개용 라벨 
    spec:
      containers:
      - image: maho/webapl3  # 컨테이너 이미지
        name: web-server-c
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-apl1
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
  selector:
    web: web-apl1