##
# 애플리케이션 개발자용 서비스 어카운트 작성
#
apiVersion: v1
kind: ServiceAccount
metadata:
  name: developer
  namespace: test
---
################################################
##
# SA와 클러스터 롤 ADMIN을 바인딩
#
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-crb
  namespace: test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  namespace: test
  name: developer

##---
##
# 애플리케이션 개발자용 롤 작성
#   클러스터롤 admin에 포함되므로 필수는 아님
#
##apiVersion: rbac.authorization.k8s.io/v1
##kind: Role
##metadata:
##  name: developer
##  namespace: test
##rules:
# 파드의 접근 권한, Core API 지정 apiVersion: v1
##- apiGroups: [""]
##  resources: ["pods","pods/log","services"]
##  verbs: ["get", "watch", "list"]
# deployment의 접근 권한,  extention/appls 지정
##- apiGroups: ["extensions", "apps"]  
## resources: ["deployments"]
##  verbs: ["get", "watch", "list"]

---
##
# SA와 developer롤 바인딩
#   (클러스터롤 admin에 포함되므로 필수는 아님)
#
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-rb
  namespace: test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: developer
subjects:
- kind: ServiceAccount
  namespace: test
  name: developer

